[package]
name = "t4_idl_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1"
nom-greedyerror = "0.4"
nom_locate = "4.0"
num-bigint = "0.4"
num-traits = "0.2"
